// Generated by gencpp from file visual_processing/SetParam.msg
// DO NOT EDIT!


#ifndef VISUAL_PROCESSING_MESSAGE_SETPARAM_H
#define VISUAL_PROCESSING_MESSAGE_SETPARAM_H

#include <ros/service_traits.h>


#include <visual_processing/SetParamRequest.h>
#include <visual_processing/SetParamResponse.h>


namespace visual_processing
{

struct SetParam
{

typedef SetParamRequest Request;
typedef SetParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetParam
} // namespace visual_processing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::visual_processing::SetParam > {
  static const char* value()
  {
    return "9346153312ad52b853d2b74ee012923e";
  }

  static const char* value(const ::visual_processing::SetParam&) { return value(); }
};

template<>
struct DataType< ::visual_processing::SetParam > {
  static const char* value()
  {
    return "visual_processing/SetParam";
  }

  static const char* value(const ::visual_processing::SetParam&) { return value(); }
};


// service_traits::MD5Sum< ::visual_processing::SetParamRequest> should match
// service_traits::MD5Sum< ::visual_processing::SetParam >
template<>
struct MD5Sum< ::visual_processing::SetParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::visual_processing::SetParam >::value();
  }
  static const char* value(const ::visual_processing::SetParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::visual_processing::SetParamRequest> should match
// service_traits::DataType< ::visual_processing::SetParam >
template<>
struct DataType< ::visual_processing::SetParamRequest>
{
  static const char* value()
  {
    return DataType< ::visual_processing::SetParam >::value();
  }
  static const char* value(const ::visual_processing::SetParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::visual_processing::SetParamResponse> should match
// service_traits::MD5Sum< ::visual_processing::SetParam >
template<>
struct MD5Sum< ::visual_processing::SetParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::visual_processing::SetParam >::value();
  }
  static const char* value(const ::visual_processing::SetParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::visual_processing::SetParamResponse> should match
// service_traits::DataType< ::visual_processing::SetParam >
template<>
struct DataType< ::visual_processing::SetParamResponse>
{
  static const char* value()
  {
    return DataType< ::visual_processing::SetParam >::value();
  }
  static const char* value(const ::visual_processing::SetParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISUAL_PROCESSING_MESSAGE_SETPARAM_H
