// Generated by gencpp from file hiwonder_servo_msgs/ActionGroupRunnerActionGoal.msg
// DO NOT EDIT!


#ifndef HIWONDER_SERVO_MSGS_MESSAGE_ACTIONGROUPRUNNERACTIONGOAL_H
#define HIWONDER_SERVO_MSGS_MESSAGE_ACTIONGROUPRUNNERACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <hiwonder_servo_msgs/ActionGroupRunnerGoal.h>

namespace hiwonder_servo_msgs
{
template <class ContainerAllocator>
struct ActionGroupRunnerActionGoal_
{
  typedef ActionGroupRunnerActionGoal_<ContainerAllocator> Type;

  ActionGroupRunnerActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  ActionGroupRunnerActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::hiwonder_servo_msgs::ActionGroupRunnerGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ActionGroupRunnerActionGoal_

typedef ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<std::allocator<void> > ActionGroupRunnerActionGoal;

typedef boost::shared_ptr< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal > ActionGroupRunnerActionGoalPtr;
typedef boost::shared_ptr< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal const> ActionGroupRunnerActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_servo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02fa077c8684bca622316f73fa90d10a";
  }

  static const char* value(const ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02fa077c8684bca6ULL;
  static const uint64_t static_value2 = 0x22316f73fa90d10aULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_servo_msgs/ActionGroupRunnerActionGoal";
  }

  static const char* value(const ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ActionGroupRunnerGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_servo_msgs/ActionGroupRunnerGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string name\n"
"uint32 repeat\n"
;
  }

  static const char* value(const ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionGroupRunnerActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_servo_msgs::ActionGroupRunnerActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::hiwonder_servo_msgs::ActionGroupRunnerGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_SERVO_MSGS_MESSAGE_ACTIONGROUPRUNNERACTIONGOAL_H
