// Generated by gencpp from file hiwonder_servo_msgs/ActionGroupRunnerResult.msg
// DO NOT EDIT!


#ifndef HIWONDER_SERVO_MSGS_MESSAGE_ACTIONGROUPRUNNERRESULT_H
#define HIWONDER_SERVO_MSGS_MESSAGE_ACTIONGROUPRUNNERRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_servo_msgs
{
template <class ContainerAllocator>
struct ActionGroupRunnerResult_
{
  typedef ActionGroupRunnerResult_<ContainerAllocator> Type;

  ActionGroupRunnerResult_()
    : name()
    , result()  {
    }
  ActionGroupRunnerResult_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> const> ConstPtr;

}; // struct ActionGroupRunnerResult_

typedef ::hiwonder_servo_msgs::ActionGroupRunnerResult_<std::allocator<void> > ActionGroupRunnerResult;

typedef boost::shared_ptr< ::hiwonder_servo_msgs::ActionGroupRunnerResult > ActionGroupRunnerResultPtr;
typedef boost::shared_ptr< ::hiwonder_servo_msgs::ActionGroupRunnerResult const> ActionGroupRunnerResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_servo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bce5bc1805b967315e9937df0cda1034";
  }

  static const char* value(const ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbce5bc1805b96731ULL;
  static const uint64_t static_value2 = 0x5e9937df0cda1034ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_servo_msgs/ActionGroupRunnerResult";
  }

  static const char* value(const ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string name\n"
"string result\n"
;
  }

  static const char* value(const ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionGroupRunnerResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_servo_msgs::ActionGroupRunnerResult_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_SERVO_MSGS_MESSAGE_ACTIONGROUPRUNNERRESULT_H
