// Generated by gencpp from file hiwonder_servo_msgs/CommandDuration.msg
// DO NOT EDIT!


#ifndef HIWONDER_SERVO_MSGS_MESSAGE_COMMANDDURATION_H
#define HIWONDER_SERVO_MSGS_MESSAGE_COMMANDDURATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_servo_msgs
{
template <class ContainerAllocator>
struct CommandDuration_
{
  typedef CommandDuration_<ContainerAllocator> Type;

  CommandDuration_()
    : data(0.0)
    , duration(0.0)  {
    }
  CommandDuration_(const ContainerAllocator& _alloc)
    : data(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef double _data_type;
  _data_type data;

   typedef double _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> const> ConstPtr;

}; // struct CommandDuration_

typedef ::hiwonder_servo_msgs::CommandDuration_<std::allocator<void> > CommandDuration;

typedef boost::shared_ptr< ::hiwonder_servo_msgs::CommandDuration > CommandDurationPtr;
typedef boost::shared_ptr< ::hiwonder_servo_msgs::CommandDuration const> CommandDurationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_servo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e962e48dbaa78de7630556894fd2bd8e";
  }

  static const char* value(const ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe962e48dbaa78de7ULL;
  static const uint64_t static_value2 = 0x630556894fd2bd8eULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_servo_msgs/CommandDuration";
  }

  static const char* value(const ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 data\n"
"float64 duration\n"
;
  }

  static const char* value(const ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandDuration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_servo_msgs::CommandDuration_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<double>::stream(s, indent + "  ", v.data);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_SERVO_MSGS_MESSAGE_COMMANDDURATION_H
