// Generated by gencpp from file hiwonder_servo_msgs/RawIdPosDur.msg
// DO NOT EDIT!


#ifndef HIWONDER_SERVO_MSGS_MESSAGE_RAWIDPOSDUR_H
#define HIWONDER_SERVO_MSGS_MESSAGE_RAWIDPOSDUR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_servo_msgs
{
template <class ContainerAllocator>
struct RawIdPosDur_
{
  typedef RawIdPosDur_<ContainerAllocator> Type;

  RawIdPosDur_()
    : id(0)
    , position(0)
    , duration(0)  {
    }
  RawIdPosDur_(const ContainerAllocator& _alloc)
    : id(0)
    , position(0)
    , duration(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint16_t _position_type;
  _position_type position;

   typedef uint16_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> const> ConstPtr;

}; // struct RawIdPosDur_

typedef ::hiwonder_servo_msgs::RawIdPosDur_<std::allocator<void> > RawIdPosDur;

typedef boost::shared_ptr< ::hiwonder_servo_msgs::RawIdPosDur > RawIdPosDurPtr;
typedef boost::shared_ptr< ::hiwonder_servo_msgs::RawIdPosDur const> RawIdPosDurConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.position == rhs.position &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator1> & lhs, const ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_servo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee63665fa0c79998dcae740d86109b84";
  }

  static const char* value(const ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee63665fa0c79998ULL;
  static const uint64_t static_value2 = 0xdcae740d86109b84ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_servo_msgs/RawIdPosDur";
  }

  static const char* value(const ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"uint16 position\n"
"uint16 duration\n"
;
  }

  static const char* value(const ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RawIdPosDur_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_servo_msgs::RawIdPosDur_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.position);
    s << indent << "duration: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_SERVO_MSGS_MESSAGE_RAWIDPOSDUR_H
