// Generated by gencpp from file intelligent_transport/SetTarget.msg
// DO NOT EDIT!


#ifndef INTELLIGENT_TRANSPORT_MESSAGE_SETTARGET_H
#define INTELLIGENT_TRANSPORT_MESSAGE_SETTARGET_H

#include <ros/service_traits.h>


#include <intelligent_transport/SetTargetRequest.h>
#include <intelligent_transport/SetTargetResponse.h>


namespace intelligent_transport
{

struct SetTarget
{

typedef SetTargetRequest Request;
typedef SetTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTarget
} // namespace intelligent_transport


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::intelligent_transport::SetTarget > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::intelligent_transport::SetTarget&) { return value(); }
};

template<>
struct DataType< ::intelligent_transport::SetTarget > {
  static const char* value()
  {
    return "intelligent_transport/SetTarget";
  }

  static const char* value(const ::intelligent_transport::SetTarget&) { return value(); }
};


// service_traits::MD5Sum< ::intelligent_transport::SetTargetRequest> should match
// service_traits::MD5Sum< ::intelligent_transport::SetTarget >
template<>
struct MD5Sum< ::intelligent_transport::SetTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::intelligent_transport::SetTarget >::value();
  }
  static const char* value(const ::intelligent_transport::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::intelligent_transport::SetTargetRequest> should match
// service_traits::DataType< ::intelligent_transport::SetTarget >
template<>
struct DataType< ::intelligent_transport::SetTargetRequest>
{
  static const char* value()
  {
    return DataType< ::intelligent_transport::SetTarget >::value();
  }
  static const char* value(const ::intelligent_transport::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::intelligent_transport::SetTargetResponse> should match
// service_traits::MD5Sum< ::intelligent_transport::SetTarget >
template<>
struct MD5Sum< ::intelligent_transport::SetTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::intelligent_transport::SetTarget >::value();
  }
  static const char* value(const ::intelligent_transport::SetTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::intelligent_transport::SetTargetResponse> should match
// service_traits::DataType< ::intelligent_transport::SetTarget >
template<>
struct DataType< ::intelligent_transport::SetTargetResponse>
{
  static const char* value()
  {
    return DataType< ::intelligent_transport::SetTarget >::value();
  }
  static const char* value(const ::intelligent_transport::SetTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTELLIGENT_TRANSPORT_MESSAGE_SETTARGET_H
