// Generated by gencpp from file intelligent_collating/SetTarget.msg
// DO NOT EDIT!


#ifndef INTELLIGENT_COLLATING_MESSAGE_SETTARGET_H
#define INTELLIGENT_COLLATING_MESSAGE_SETTARGET_H

#include <ros/service_traits.h>


#include <intelligent_collating/SetTargetRequest.h>
#include <intelligent_collating/SetTargetResponse.h>


namespace intelligent_collating
{

struct SetTarget
{

typedef SetTargetRequest Request;
typedef SetTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTarget
} // namespace intelligent_collating


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::intelligent_collating::SetTarget > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::intelligent_collating::SetTarget&) { return value(); }
};

template<>
struct DataType< ::intelligent_collating::SetTarget > {
  static const char* value()
  {
    return "intelligent_collating/SetTarget";
  }

  static const char* value(const ::intelligent_collating::SetTarget&) { return value(); }
};


// service_traits::MD5Sum< ::intelligent_collating::SetTargetRequest> should match
// service_traits::MD5Sum< ::intelligent_collating::SetTarget >
template<>
struct MD5Sum< ::intelligent_collating::SetTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::intelligent_collating::SetTarget >::value();
  }
  static const char* value(const ::intelligent_collating::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::intelligent_collating::SetTargetRequest> should match
// service_traits::DataType< ::intelligent_collating::SetTarget >
template<>
struct DataType< ::intelligent_collating::SetTargetRequest>
{
  static const char* value()
  {
    return DataType< ::intelligent_collating::SetTarget >::value();
  }
  static const char* value(const ::intelligent_collating::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::intelligent_collating::SetTargetResponse> should match
// service_traits::MD5Sum< ::intelligent_collating::SetTarget >
template<>
struct MD5Sum< ::intelligent_collating::SetTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::intelligent_collating::SetTarget >::value();
  }
  static const char* value(const ::intelligent_collating::SetTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::intelligent_collating::SetTargetResponse> should match
// service_traits::DataType< ::intelligent_collating::SetTarget >
template<>
struct DataType< ::intelligent_collating::SetTargetResponse>
{
  static const char* value()
  {
    return DataType< ::intelligent_collating::SetTarget >::value();
  }
  static const char* value(const ::intelligent_collating::SetTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTELLIGENT_COLLATING_MESSAGE_SETTARGET_H
