// Generated by gencpp from file color_tracking/SetTarget.msg
// DO NOT EDIT!


#ifndef COLOR_TRACKING_MESSAGE_SETTARGET_H
#define COLOR_TRACKING_MESSAGE_SETTARGET_H

#include <ros/service_traits.h>


#include <color_tracking/SetTargetRequest.h>
#include <color_tracking/SetTargetResponse.h>


namespace color_tracking
{

struct SetTarget
{

typedef SetTargetRequest Request;
typedef SetTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTarget
} // namespace color_tracking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::color_tracking::SetTarget > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::color_tracking::SetTarget&) { return value(); }
};

template<>
struct DataType< ::color_tracking::SetTarget > {
  static const char* value()
  {
    return "color_tracking/SetTarget";
  }

  static const char* value(const ::color_tracking::SetTarget&) { return value(); }
};


// service_traits::MD5Sum< ::color_tracking::SetTargetRequest> should match
// service_traits::MD5Sum< ::color_tracking::SetTarget >
template<>
struct MD5Sum< ::color_tracking::SetTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::color_tracking::SetTarget >::value();
  }
  static const char* value(const ::color_tracking::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::color_tracking::SetTargetRequest> should match
// service_traits::DataType< ::color_tracking::SetTarget >
template<>
struct DataType< ::color_tracking::SetTargetRequest>
{
  static const char* value()
  {
    return DataType< ::color_tracking::SetTarget >::value();
  }
  static const char* value(const ::color_tracking::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::color_tracking::SetTargetResponse> should match
// service_traits::MD5Sum< ::color_tracking::SetTarget >
template<>
struct MD5Sum< ::color_tracking::SetTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::color_tracking::SetTarget >::value();
  }
  static const char* value(const ::color_tracking::SetTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::color_tracking::SetTargetResponse> should match
// service_traits::DataType< ::color_tracking::SetTarget >
template<>
struct DataType< ::color_tracking::SetTargetResponse>
{
  static const char* value()
  {
    return DataType< ::color_tracking::SetTarget >::value();
  }
  static const char* value(const ::color_tracking::SetTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLOR_TRACKING_MESSAGE_SETTARGET_H
