// Generated by gencpp from file intelligent_carry/SetTarget.msg
// DO NOT EDIT!


#ifndef INTELLIGENT_CARRY_MESSAGE_SETTARGET_H
#define INTELLIGENT_CARRY_MESSAGE_SETTARGET_H

#include <ros/service_traits.h>


#include <intelligent_carry/SetTargetRequest.h>
#include <intelligent_carry/SetTargetResponse.h>


namespace intelligent_carry
{

struct SetTarget
{

typedef SetTargetRequest Request;
typedef SetTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTarget
} // namespace intelligent_carry


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::intelligent_carry::SetTarget > {
  static const char* value()
  {
    return "546971982e3fbbd5a41e60fb6432e357";
  }

  static const char* value(const ::intelligent_carry::SetTarget&) { return value(); }
};

template<>
struct DataType< ::intelligent_carry::SetTarget > {
  static const char* value()
  {
    return "intelligent_carry/SetTarget";
  }

  static const char* value(const ::intelligent_carry::SetTarget&) { return value(); }
};


// service_traits::MD5Sum< ::intelligent_carry::SetTargetRequest> should match
// service_traits::MD5Sum< ::intelligent_carry::SetTarget >
template<>
struct MD5Sum< ::intelligent_carry::SetTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::intelligent_carry::SetTarget >::value();
  }
  static const char* value(const ::intelligent_carry::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::intelligent_carry::SetTargetRequest> should match
// service_traits::DataType< ::intelligent_carry::SetTarget >
template<>
struct DataType< ::intelligent_carry::SetTargetRequest>
{
  static const char* value()
  {
    return DataType< ::intelligent_carry::SetTarget >::value();
  }
  static const char* value(const ::intelligent_carry::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::intelligent_carry::SetTargetResponse> should match
// service_traits::MD5Sum< ::intelligent_carry::SetTarget >
template<>
struct MD5Sum< ::intelligent_carry::SetTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::intelligent_carry::SetTarget >::value();
  }
  static const char* value(const ::intelligent_carry::SetTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::intelligent_carry::SetTargetResponse> should match
// service_traits::DataType< ::intelligent_carry::SetTarget >
template<>
struct DataType< ::intelligent_carry::SetTargetResponse>
{
  static const char* value()
  {
    return DataType< ::intelligent_carry::SetTarget >::value();
  }
  static const char* value(const ::intelligent_carry::SetTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTELLIGENT_CARRY_MESSAGE_SETTARGET_H
