; Auto-generated. Do not edit!


(cl:in-package hiwonder_servo_msgs-msg)


;//! \htmlinclude ActionGroupRunnerFeedback.msg.html

(cl:defclass <ActionGroupRunnerFeedback> (roslisp-msg-protocol:ros-message)
  ((name
    :reader name
    :initarg :name
    :type cl:string
    :initform "")
   (step
    :reader step
    :initarg :step
    :type cl:integer
    :initform 0))
)

(cl:defclass ActionGroupRunnerFeedback (<ActionGroupRunnerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActionGroupRunnerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActionGroupRunnerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hiwonder_servo_msgs-msg:<ActionGroupRunnerFeedback> is deprecated: use hiwonder_servo_msgs-msg:ActionGroupRunnerFeedback instead.")))

(cl:ensure-generic-function 'name-val :lambda-list '(m))
(cl:defmethod name-val ((m <ActionGroupRunnerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hiwonder_servo_msgs-msg:name-val is deprecated.  Use hiwonder_servo_msgs-msg:name instead.")
  (name m))

(cl:ensure-generic-function 'step-val :lambda-list '(m))
(cl:defmethod step-val ((m <ActionGroupRunnerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hiwonder_servo_msgs-msg:step-val is deprecated.  Use hiwonder_servo_msgs-msg:step instead.")
  (step m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActionGroupRunnerFeedback>) ostream)
  "Serializes a message object of type '<ActionGroupRunnerFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'name))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'step)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'step)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'step)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'step)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActionGroupRunnerFeedback>) istream)
  "Deserializes a message object of type '<ActionGroupRunnerFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'step)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'step)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'step)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'step)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActionGroupRunnerFeedback>)))
  "Returns string type for a message object of type '<ActionGroupRunnerFeedback>"
  "hiwonder_servo_msgs/ActionGroupRunnerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActionGroupRunnerFeedback)))
  "Returns string type for a message object of type 'ActionGroupRunnerFeedback"
  "hiwonder_servo_msgs/ActionGroupRunnerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActionGroupRunnerFeedback>)))
  "Returns md5sum for a message object of type '<ActionGroupRunnerFeedback>"
  "be888268ba53e256c1e062ac34ecaafc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActionGroupRunnerFeedback)))
  "Returns md5sum for a message object of type 'ActionGroupRunnerFeedback"
  "be888268ba53e256c1e062ac34ecaafc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActionGroupRunnerFeedback>)))
  "Returns full string definition for message of type '<ActionGroupRunnerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string name~%uint32 step~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActionGroupRunnerFeedback)))
  "Returns full string definition for message of type 'ActionGroupRunnerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string name~%uint32 step~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActionGroupRunnerFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'name))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActionGroupRunnerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ActionGroupRunnerFeedback
    (cl:cons ':name (name msg))
    (cl:cons ':step (step msg))
))
