; Auto-generated. Do not edit!


(cl:in-package hiwonder_servo_msgs-msg)


;//! \htmlinclude ActionGroupRunnerGoal.msg.html

(cl:defclass <ActionGroupRunnerGoal> (roslisp-msg-protocol:ros-message)
  ((name
    :reader name
    :initarg :name
    :type cl:string
    :initform "")
   (repeat
    :reader repeat
    :initarg :repeat
    :type cl:integer
    :initform 0))
)

(cl:defclass ActionGroupRunnerGoal (<ActionGroupRunnerGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActionGroupRunnerGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActionGroupRunnerGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hiwonder_servo_msgs-msg:<ActionGroupRunnerGoal> is deprecated: use hiwonder_servo_msgs-msg:ActionGroupRunnerGoal instead.")))

(cl:ensure-generic-function 'name-val :lambda-list '(m))
(cl:defmethod name-val ((m <ActionGroupRunnerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hiwonder_servo_msgs-msg:name-val is deprecated.  Use hiwonder_servo_msgs-msg:name instead.")
  (name m))

(cl:ensure-generic-function 'repeat-val :lambda-list '(m))
(cl:defmethod repeat-val ((m <ActionGroupRunnerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hiwonder_servo_msgs-msg:repeat-val is deprecated.  Use hiwonder_servo_msgs-msg:repeat instead.")
  (repeat m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActionGroupRunnerGoal>) ostream)
  "Serializes a message object of type '<ActionGroupRunnerGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'name))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'repeat)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'repeat)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'repeat)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'repeat)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActionGroupRunnerGoal>) istream)
  "Deserializes a message object of type '<ActionGroupRunnerGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'repeat)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'repeat)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'repeat)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'repeat)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActionGroupRunnerGoal>)))
  "Returns string type for a message object of type '<ActionGroupRunnerGoal>"
  "hiwonder_servo_msgs/ActionGroupRunnerGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActionGroupRunnerGoal)))
  "Returns string type for a message object of type 'ActionGroupRunnerGoal"
  "hiwonder_servo_msgs/ActionGroupRunnerGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActionGroupRunnerGoal>)))
  "Returns md5sum for a message object of type '<ActionGroupRunnerGoal>"
  "25bab19f14cbfba689c136edaf583c54")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActionGroupRunnerGoal)))
  "Returns md5sum for a message object of type 'ActionGroupRunnerGoal"
  "25bab19f14cbfba689c136edaf583c54")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActionGroupRunnerGoal>)))
  "Returns full string definition for message of type '<ActionGroupRunnerGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string name~%uint32 repeat~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActionGroupRunnerGoal)))
  "Returns full string definition for message of type 'ActionGroupRunnerGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string name~%uint32 repeat~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActionGroupRunnerGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'name))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActionGroupRunnerGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ActionGroupRunnerGoal
    (cl:cons ':name (name msg))
    (cl:cons ':repeat (repeat msg))
))
